### ISSUE TITLE
Perm manquante 

### ISSUE THREAD

**Issue by Emilien52** [Florentlife/CraftMyWebsite#209]
Dans "Accès Panel" >> NewsLetter

Dans "Permission Panel":
>> (boutique) Page Historique d'achat
>> (vote) Page Récompenses Auto

**Comment by Florentlife** [comment]
Accès page Newsletter => En cours

**Comment by Florentlife** [comment]
Accès page historique achat => en cours
Accès page récompense auto => en cours

**Comment by Florentlife** [comment]
Réglé
