### ISSUE TITLE
Envoi de mails newsletter oublie le dernier mail de la liste

### ISSUE THREAD

**Issue by veilleurj** [Florentlife/CraftMyWebsite#215]
Il y a une correction à apporter dans le code pour permettre la prise en compte de la bonne quantité de mails a qui on envoie une newsletter
aujourd'hui l'envoie de la NL oublie le dernier destinataire, cela est du a une erreur de longueur de boucle dans le code en question.

**Comment by veilleurj** [comment]
dans le fichier newsletter du dossier admin ligne 303
	function sendMail() {
		i = $indexMailPlayer;
		if(i < allEMail.length-2) // remplacer par length-1

**Comment by veilleurj** [comment]
![image](https://user-images.githubusercontent.com/783684/80590369-0cff5980-8a1c-11ea-9c8e-e0f530435edd.png)

**Comment by veilleurj** [comment]
après correction : 
![image](https://user-images.githubusercontent.com/783684/80590514-49cb5080-8a1c-11ea-82d9-a9369c6ceb49.png)

**Comment by Florentlife** [comment]
On regardera ! ;) Merci !!!

**Comment by Emilien52** [comment]
ça a été résolu !

Merci du signalement 👍
