### ISSUE TITLE
[JsonAPI] Erreur Undefined variable "c"

### ISSUE THREAD

**Issue by PinglsDzn** [Florentlife/CraftMyWebsite#227]
_Copie de PinglsDzn/CraftMyAdmin_
### Reporté à Florentlife
Erreur de _json.class.php_ reporté à @Florentlife sur [#github (604710918592528384) ](https://discordapp.com/channels/557178315471978515/604710918592528384/71166326317934182)
J'attend sont retour savoir si c'est normal ou pas cas contraire faudra patché ça et sur neocraft/ndd/panel et sur le git [Florentlife/CraftMyWebsite](https://github.com/Florentlife/CraftMyWebsite)

`
Notice: Undefined variable: c in /var/www/vhosts/neocraft.fr/httpdocs/ndd/panel/controleur/json/json.class.php on line 68
`

> Je crée une issue car ça me stress d'avoir l'erreur une fois sur deux, mais on a besoin du error reporting car on et pas en prod 😁

**Comment by Florentlife** [comment]
A tester mais normalement c'est fait
