### ISSUE TITLE
Perm page Upload

### ISSUE THREAD

**Issue by Ethanox** [Florentlife/CraftMyWebsite#92]
Plop, la perm pour afficher le lien vers la page "Upload" (sidebar.php) est la même que celle pour afficher le lien vers la page "maintenance"
voir: https://github.com/Florentlife/CMW-V1.7/blob/Developpement/admin/include/sidebar.php#L92

**Comment by Florentlife** [comment]
En cours

**Comment by Florentlife** [comment]
Réglé
